### ISSUE TITLE
Automated the manifest file

### ISSUE THREAD

**Issue by HelmutLety** [meilisearch/meilisearch-kubernetes#39] opened 2020-12-11 09:40 UTC
We having a redundancy between the chart file and the meilisearch.yaml file in Manifest. Which is not a bad thing. Although, it may be good to have the manifest file created automatically when a change is done in the charts, or at least compared, during a pipeline.

What do you guys think? We having now the possibility that we changing the charts, and forgetting about the manifest, and this one will not correspond to it any more.

**Comment by eskombro** [comment] 2020-12-14 10:11
Hi @HelmutLety 

This seems to be a duplicate of https://github.com/meilisearch/meilisearch-kubernetes/issues/12

Totally agree with this, but would be better to discuss it there? :)

**Closed by eskombro** 2020-12-14 10:11 UTC

**Comment by HelmutLety** [comment] 2020-12-14 10:12
Oh yes! sorry didn't saw that :)
